### ISSUE TITLE
pytests method fails 

### ISSUE THREAD

**Issue by navalev** [nschloe/pytest-codeblocks#33]
testing pytests method on a readme file fails with "function pytests.<locals>.exec_raise at 0x000001DB8B537160>" message. 
extract method runs sucessfully on the same file

**Comment by nschloe** [comment]
I would need an mwe to reproduce.

**Comment by navalev** [comment]
sure. Run the code on this repo:

```python
import os
import exdown

for root, dirs, files in os.walk("."):
  for file in files:
      if file.endswith(".md"):
        filename = os.path.join(root,file)
        print(filename)
        blocks = exdown.extract(filename, encoding=None, syntax_filter="python")
        print(blocks)
        tests = exdown.pytests(filename, encoding=None, syntax_filter="python")
        print(tests)
```

result:
```
.\README.md
[('import exdown\n\nblocks = exdown.extract("README.md")\n', 25), ('import exdown\n\ntest_readme = exdown.pytests("README.md")\n', 31), ('exdown.pytests("README.md", syntax_filter="python")\n', 38)]
<function pytests.<locals>.exec_raise at 0x00000246D80E7160>
.\test\example.md
[('1 + 1\n', 1), ('1 + 2 + 3\n2 + 5\n', 5), ('import exdown\n\nexdown.from_buffer\n', 10), ('# ```import math```\n', 26), ('1 + 1 == 2\n', 31), ('1 + 1 == 2\n', 36)]
<function pytests.<locals>.exec_raise at 0x00000246D8775550>
```
testing on python 3.8.8, with the latest exdown package 0.8.8

**Comment by nschloe** [comment]
Uhm, so this is now how you use `exdown.pytests`. What are you trying to do exactly?

**Comment by navalev** [comment]
followed the readme in this repo, trying to test out the code samples in the readmes. I can just try/catch and exec each block retruned from the extract method, but from the samples u provided it seems that the pytests method does that.

**Comment by nschloe** [comment]
Yeah, in your file
```
test/test_readme.py
```
you just need the line
```
import exdown

test_readme = exdown.pytest("README.md")
```
and it should work. The "variable" `test_readme` is actually a decorated function that pytest will pick up. If you want to add tests from more files, you do
```
tests2 = exdown.pytest("foo.md")
test_myversion = exdown.pytest("bar.md")
```
etc. Just make sure the variable name starts with `test` so pytest uses it.

**Comment by navalev** [comment]
I would expect pytests to raise an error in case the code in the readme fails, it currently does not (or hides the error)

**Comment by nschloe** [comment]
What makes you think it doesn't do that?

**Comment by navalev** [comment]
tested on a fail code sample, it does not raise an error. Am I missing something?

**Comment by nschloe** [comment]
Are you talking about the code [here](https://github.com/nschloe/exdown/issues/33#issuecomment-826896539)? You override the `tests` variable in every iteration of the loop, and pytest will only be able to discover the last one of them. Perhaps that's the issue?

**Comment by navalev** [comment]
it does not yiled any errors even when runing on a single file with a single code snippet.

**Comment by nschloe** [comment]
What are you running exactly and how?

**Comment by navalev** [comment]
Use this package to extract all python code from readme files, and execute it to check validity.

**Comment by nschloe** [comment]
Sure, let's see some code.

**Comment by nschloe** [comment]
I changed many things about exdown, so this can probably be closed.

**Comment by navalev** [comment]
thosr are a lot of changes :) I see the pytests method was removed.
