### ISSUE TITLE
 embed codeblock results on README?

### ISSUE THREAD

**Issue by krober10nd** [nschloe/pytest-codeblocks#56]
* Could there be a mechanism added to this package for when a REAMDE code block is executed to embed the produced images /results directly onto the README automatically? 
* I realize this somewhat falls beyond the scope of testing the code block strictly. However, since you open the possibility to test code written on a README with this package, I think naturally it would be useful to have some way to embed the images (or in general result(s)) onto the README without having to manually upload the images to Github and relink them in the README.

**Comment by nschloe** [comment]
Tough. How do you include images in your README? I usually put them in the gh-pages branch and source them from there. It seems to me that this could perhaps be done by a gh-action when pulling to main/master. Perhaps pytest-codeblocks could indeed be of help here.

**Comment by krober10nd** [comment]
Whoops accidentally hit the button. Sounds good.

**Comment by nschloe** [comment]
How do you include images in your README?

**Comment by krober10nd** [comment]
I work on the README then make the images "offline" and then drag and drop them to a random issue box to get the link. Then place the link in the correct space in the README.

**Comment by nschloe** [comment]
I came to visit this again and it seems to me now that this should be a separate tool. `pytest-codeblocks` only runs pytests on the code block. You can add something like `expected-output`, but generating images, and uploading pushing them somewhere seems out of scope.
