### ISSUE TITLE
"could not get source code"

### ISSUE THREAD

**Issue by IceTDrinker** [nschloe/pytest-codeblocks#57]
Hello I am getting this error message with a project that uses a native extension I cannot share.

Any idea as to what is going on (exec not being able to load it ?) or what kind of workaround could be used ?

**Comment by nschloe** [comment]
Probably a network error. Probably not related to pytest-codeblocks, and impossible to debug here without further details.

**Comment by IceTDrinker** [comment]
> Probably a network error. Probably not related to pytest-codeblocks, and impossible to debug here without further details.

Network error ? Could you elaborate ? I'm not using network in the code.

Other specificity, some code uses the PYTHONPATH to be loaded.

If you don't have a clue no problem. I understand it's hard to debug when I can't provide a minimal example...

**Comment by nschloe** [comment]
Yeah, there's no way for me to debug here. Feel free to reopen if you can provide a minimal example.

**Comment by IceTDrinker** [comment]
hello @nschloe I used a small change locally where I first compile the code to bytecode and then exec that and fixes my issue.

Is it ok if I submit the patch to your project ?

**Comment by nschloe** [comment]
I don't know what you mean exactly. You can just submit a PR and then we'll know what we talk about.
